version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: theme-builder-postgres
    environment:
      POSTGRES_DB: theme_builder
      POSTGRES_USER: theme_builder
      POSTGRES_PASSWORD: theme_builder_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - theme-builder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U theme_builder"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin - Database Management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: theme-builder-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@themebuilder.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - theme-builder-network
    depends_on:
      - postgres

  # Backend - Symfony API (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: theme-builder-backend
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
      APP_SECRET: change_me_in_production
      DATABASE_URL: postgresql://theme_builder:theme_builder_password@postgres:5432/theme_builder?serverVersion=16&charset=utf8
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    networks:
      - theme-builder-network
    depends_on:
      postgres:
        condition: service_healthy

  # Nginx - Web Server for Backend API
  nginx:
    image: nginx:alpine
    container_name: theme-builder-nginx
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - theme-builder-network
    depends_on:
      - backend

  # Theme Builder - React + Vite Dev Server
  theme-builder:
    image: node:20-alpine
    container_name: theme-builder-app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./theme-builder:/app
      - theme_builder_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - theme-builder-network
    depends_on:
      - nginx

  # Demo Shop - React Router + Vite Dev Server
  demo-shop:
    image: node:20-alpine
    container_name: theme-builder-demo-shop
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./demo-shop:/app
      - demo_shop_node_modules:/app/node_modules
    ports:
      - "5174:5173"
    networks:
      - theme-builder-network
    depends_on:
      - nginx

networks:
  theme-builder-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  backend_vendor:
  theme_builder_node_modules:
  demo_shop_node_modules:
