doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # PostgreSQL 16 - configured for theme-builder database
        driver: 'pdo_pgsql'
        server_version: '16'
        charset: utf8

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        # Map PostgreSQL custom enum types to string
        mapping_types:
            page_type_enum: string

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

        # PostgreSQL uses IDENTITY for primary key generation
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity

        auto_mapping: true

        mappings:
            # Main application entities and embeddables
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model'
                prefix: 'App\Model'
                alias: App

        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
